name: node-test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "23 4 * * *"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}

      - name: npm install, build, and test
        run: |
          npm ci
          npm run build --if-present
          npm run lint
          npm run coverage
        env:
          CI: true
          TEST_HC_HOST: ${{ secrets.TEST_HC_HOST }}
          TEST_HC_PORT: ${{ secrets.TEST_HC_PORT }}
          TEST_HC_USER: ${{ secrets.TEST_HC_USER }}
          TEST_HC_PASSWORD: ${{ secrets.TEST_HC_PASSWORD }}

      - name: upload coverage
        uses: codecov/codecov-action@v1
