name: node-release

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org/

      - name: npm test
        run: |
          npm ci
          npm test
          npm shrinkwrap
        env:
          CI: true
          TEST_HC_HOST: ${{ secrets.TEST_HC_HOST }}
          TEST_HC_PORT: ${{ secrets.TEST_HC_PORT }}
          TEST_HC_USER: ${{ secrets.TEST_HC_USER }}
          TEST_HC_PASSWORD: ${{ secrets.TEST_HC_PASSWORD }}

      - name: npm auth & publish
        run: npm run build && npm publish --tag latest
        env:
          NODE_AUTH_TOKEN: ${{secrets.Z_NPM_TOKEN}}
